#This is the config file of AdvancedPvP.

#Kit and arena data are stored locally, whereas player and level data are stored in a MySQL Database. The plugin will automaticly create the required tables.

#NOTE: Make sure the MySQL account has permissions: SELECT, UPDATE, INSERT and CREATE TABLE.

#MySQL login info.
MySQL-Host:
MySQL-Port:
MySQL-DB_Name:
MySQL-User:
MySQL-Password:

#This determines the player´s chat channel when they join.
default-channel: lobby