name: AdvancedPvP
main: me.eelek.advancedpvp.APvPMain
version: 2.0
author: Eelek
website: https://eelekweb.tk/
description: The Advanced PvP plugin by Eelek.
api-version: 1.13

commands:
  kit:
    description: The main command.
  arena:
    description: Arena command.