name: AdvancedKits
main: me.eelek.advancedkits.AKitsMain
version: 4.0
author: Eelek
description: The Advanced Kits plugin by Eelek.

commands:
  kit:
    usage: /<command>
    description: The main command.
  arena:
    usage: /<command>
    description: Arena command.